// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLIWrtWZOZge-m3X9jis5fuJjZWL94kY',
    appId: '1:878493758920:web:d2296befa180dc302cbcfd',
    messagingSenderId: '878493758920',
    projectId: 'jankenonline-d4ea1',
    authDomain: 'jankenonline-d4ea1.firebaseapp.com',
    databaseURL: 'https://jankenonline-d4ea1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jankenonline-d4ea1.appspot.com',
    measurementId: 'G-3F9R67492F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9InJo20g2_8cvTVMf9rkXKbqaaF0W-Q',
    appId: '1:878493758920:android:7c9a6238ee23cb472cbcfd',
    messagingSenderId: '878493758920',
    projectId: 'jankenonline-d4ea1',
    databaseURL: 'https://jankenonline-d4ea1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jankenonline-d4ea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkyTgVRrrcunwFsgO2wYYFtU3b4dAlqk',
    appId: '1:878493758920:ios:b8f24e983aebfaac2cbcfd',
    messagingSenderId: '878493758920',
    projectId: 'jankenonline-d4ea1',
    databaseURL: 'https://jankenonline-d4ea1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jankenonline-d4ea1.appspot.com',
    iosClientId: '878493758920-if54pbgfo24dr3tne2t22lei640itn02.apps.googleusercontent.com',
    iosBundleId: 'com.shinken.flutterShinkenOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQkyTgVRrrcunwFsgO2wYYFtU3b4dAlqk',
    appId: '1:878493758920:ios:4f968323589ab1be2cbcfd',
    messagingSenderId: '878493758920',
    projectId: 'jankenonline-d4ea1',
    databaseURL: 'https://jankenonline-d4ea1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jankenonline-d4ea1.appspot.com',
    iosClientId: '878493758920-937vn10iib8m391j09cudjh054ph2ftc.apps.googleusercontent.com',
    iosBundleId: 'com.shinken.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKLIWrtWZOZge-m3X9jis5fuJjZWL94kY',
    appId: '1:878493758920:web:cdef82ce4f15cfe22cbcfd',
    messagingSenderId: '878493758920',
    projectId: 'jankenonline-d4ea1',
    authDomain: 'jankenonline-d4ea1.firebaseapp.com',
    databaseURL: 'https://jankenonline-d4ea1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jankenonline-d4ea1.appspot.com',
    measurementId: 'G-W2B8MP05D1',
  );
}
